package com.zzy.bean;

public enum Status {
	BOOK_IS_NULL,
	AUTHOR_IS_NULL,
	BOOK_ISBN_EXIST,
	AUTHOR_NOT_EXIST,
	SQL_ERROR,
	ADD_BOOK_SUCCESS,
	ADD_AUTHOR_SUCCESS,
	ADD_AUTHOR_AND_BOOK_SUCESS,
	
	UPDATE_BOOK_SUCCESS,
	UPDATE_AUTHOR_SUCESS,
	
}
